---
before_install:
  - composer config -g github-oauth.github.com ${GITHUB_TOKEN}

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

before_script:
  - git config --global user.name "hpc-nuist-ap"
  - git config --global user.email "hpc-nuist-ap@users.noreply.github.com"

script:
  - hugo

deploy:
  - provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    skip_cleanup: true
    on:
      branch: source # or master if you are using the two-repository approach